/* The following code was generated by JFlex 1.4.3 on 2/9/22, 7:21 PM */

import java_cup.runtime.Symbol;

import java.io.File;
import java.io.FileInputStream;
// import sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/9/22, 7:21 PM from the specification file
 * <tt>src/Lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  public static final int EOF = 0;
  public static final int error = 1;
  public static final int VOID = 3;
  public static final int WHILE = 4;
  public static final int EXTENDS = 5;
  public static final int FOR = 6;
  public static final int CLASS = 7;
  public static final int NEW = 8;
  public static final int RETURN = 9;
  public static final int STATIC = 10;
  public static final int THIS = 11;
  public static final int IF = 38;
  public static final int CHAR = 39;
  public static final int ASSIGN = 40; // =
  public static final int SEMI = 41; // ;
  public static final int OR = 42; // ||
  public static final int COMMA = 43; // ,
  public static final int EQ = 44; // ==
  public static final int DOT = 45; // .
  public static final int BOOL = 45; // true/false
  public static final int LEQ = 45; // <=
  public static final int PLUS = 45; // +
  public static final int GT = 46; // >
  public static final int TIMES = 47; // *
  public static final int RBRACE = 48; // }
  public static final int LBRACKET = 49; // [
  public static final int NEQ = 50; // !=
  public static final int LPAREN = 51; // (
  public static final int AND = 52;
  public static final int DIV = 53; // /
  public static final int INT = 54;
  public static final int MINUS = 55;
  public static final int RBRACKET = 56;
  public static final int LBRACE = 57;
  public static final int IDENT = 58; // identifier
  public static final int LT = 59; // <
  public static final int RPAREN = 60; // )
  public static final int GEQ = 61; // >=
  public static final int MOD = 62; // %


  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\3\1\2\1\0\1\3\1\1\22\0\1\10\1\41\3\7"+
    "\1\37\1\44\1\6\1\51\1\52\1\36\1\34\1\47\1\35\1\50"+
    "\1\4\12\5\1\7\1\46\1\42\1\40\1\43\2\7\32\21\1\53"+
    "\1\7\1\54\1\7\1\22\1\7\1\16\1\21\1\23\1\31\1\14"+
    "\1\15\1\21\1\32\1\24\2\21\1\17\1\21\1\25\1\30\2\21"+
    "\1\12\1\20\1\11\1\13\1\27\1\26\1\33\2\21\1\55\1\45"+
    "\1\56\1\7\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\0\12\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\0\1\12\1\13\2\0\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\1\1\0\5\4\1\25\3\4\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\5\4\1\35\2\4\1\36"+
    "\4\4\1\37\2\4\1\40\1\41\1\42\1\4\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\136\0\136\0\136\0\136\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\136\0\136\0\136\0\136\0\136\0\136"+
    "\0\136\0\136\0\136\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6"+
    "\0\u04f5\0\u0524\0\u0178\0\u0553\0\u0582\0\u05b1\0\136\0\136"+
    "\0\136\0\136\0\136\0\136\0\136\0\u05e0\0\u060f\0\u063e"+
    "\0\u066d\0\u069c\0\u0178\0\u06cb\0\u06fa\0\u0178\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u0178\0\u07e5\0\u0814\0\u0178\0\u0178\0\u0178"+
    "\0\u0843\0\u0178";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\2\3\1\4\1\5\1\6\1\0\1\3"+
    "\1\7\1\10\1\11\1\12\1\13\4\11\1\0\1\14"+
    "\1\15\1\16\1\17\1\20\4\11\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\2\0\1\3\137\0\1\44\57\0\1\5\55\0\53\45"+
    "\5\0\1\11\3\0\1\11\1\46\21\11\30\0\1\11"+
    "\3\0\3\11\1\47\17\11\30\0\1\11\3\0\23\11"+
    "\30\0\1\11\3\0\22\11\1\50\30\0\1\11\3\0"+
    "\5\11\1\51\15\11\30\0\1\11\3\0\6\11\1\52"+
    "\14\11\30\0\1\11\3\0\4\11\1\53\16\11\30\0"+
    "\1\11\3\0\3\11\1\54\17\11\30\0\1\11\3\0"+
    "\21\11\1\55\1\11\30\0\1\11\3\0\17\11\1\56"+
    "\3\11\63\0\1\57\56\0\1\60\56\0\1\61\56\0"+
    "\1\62\62\0\1\63\57\0\1\64\11\0\1\44\1\2"+
    "\1\3\54\44\6\0\1\65\55\0\1\11\3\0\2\11"+
    "\1\66\20\11\30\0\1\11\3\0\1\67\22\11\30\0"+
    "\1\11\3\0\1\70\22\11\30\0\1\11\3\0\6\11"+
    "\1\71\14\11\30\0\1\11\3\0\5\11\1\72\15\11"+
    "\30\0\1\11\3\0\15\11\1\73\5\11\30\0\1\11"+
    "\3\0\13\11\1\74\7\11\30\0\1\11\3\0\13\11"+
    "\1\75\7\11\30\0\1\11\3\0\3\11\1\76\17\11"+
    "\30\0\1\11\3\0\2\11\1\77\20\11\30\0\1\11"+
    "\3\0\3\11\1\100\17\11\30\0\1\11\3\0\7\11"+
    "\1\66\13\11\30\0\1\11\3\0\7\11\1\101\13\11"+
    "\30\0\1\11\3\0\6\11\1\102\14\11\30\0\1\11"+
    "\3\0\20\11\1\103\2\11\30\0\1\11\3\0\1\11"+
    "\1\104\21\11\30\0\1\11\3\0\14\11\1\105\6\11"+
    "\30\0\1\11\3\0\7\11\1\106\13\11\30\0\1\11"+
    "\3\0\3\11\1\107\17\11\30\0\1\11\3\0\14\11"+
    "\1\110\6\11\30\0\1\11\3\0\20\11\1\111\2\11"+
    "\30\0\1\11\3\0\7\11\1\112\13\11\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2162];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\2\1\1\0\12\1\4\11\1\1"+
    "\1\0\2\1\2\0\11\11\1\1\1\0\11\1\7\11"+
    "\25\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Symbol newSymbol(int type) {
		return new Symbol(type, yyline + 1, yycolumn + 1);
	}

	private Symbol newSymbol(int type, Object value) {
		return new Symbol(type, yyline + 1, yycolumn + 1, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 35: 
          { return newSymbol(this.EXTENDS);
          }
        case 36: break;
        case 24: 
          { return newSymbol(this.LEQ);
          }
        case 37: break;
        case 5: 
          { return newSymbol(this.PLUS);
          }
        case 38: break;
        case 11: 
          { return newSymbol(this.GT);
          }
        case 39: break;
        case 22: 
          { return newSymbol(this.EQ);
          }
        case 40: break;
        case 7: 
          { return newSymbol(this.TIMES);
          }
        case 41: break;
        case 27: 
          { return newSymbol(this.OR);
          }
        case 42: break;
        case 20: 
          { return newSymbol(this.RBRACE);
          }
        case 43: break;
        case 13: 
          { return newSymbol(this.COMMA);
          }
        case 44: break;
        case 14: 
          { return newSymbol(this.DOT);
          }
        case 45: break;
        case 17: 
          { return newSymbol(this.LBRACKET);
          }
        case 46: break;
        case 9: 
          { return newSymbol(this.ASSIGN);
          }
        case 47: break;
        case 23: 
          { return newSymbol(this.NEQ);
          }
        case 48: break;
        case 34: 
          { return newSymbol(this.RETURN);
          }
        case 49: break;
        case 15: 
          { return newSymbol(this.LPAREN);
          }
        case 50: break;
        case 12: 
          { return newSymbol(this.SEMI);
          }
        case 51: break;
        case 26: 
          { return newSymbol(this.AND);
          }
        case 52: break;
        case 2: 
          { return newSymbol(this.DIV);
          }
        case 53: break;
        case 28: 
          { return newSymbol(this.CHAR, yytext().charAt(1));
          }
        case 54: break;
        case 3: 
          { return newSymbol(this.INT, yytext());
          }
        case 55: break;
        case 31: 
          { return newSymbol(this.VOID);
          }
        case 56: break;
        case 6: 
          { return newSymbol(this.MINUS);
          }
        case 57: break;
        case 29: 
          { return newSymbol(this.NEW);
          }
        case 58: break;
        case 33: 
          { return newSymbol(this.WHILE);
          }
        case 59: break;
        case 21: 
          { return newSymbol(this.IF);
          }
        case 60: break;
        case 18: 
          { return newSymbol(this.RBRACKET);
          }
        case 61: break;
        case 19: 
          { return newSymbol(this.LBRACE);
          }
        case 62: break;
        case 4: 
          { return newSymbol(this.IDENT, yytext());
          }
        case 63: break;
        case 30: 
          { return newSymbol(this.BOOL, Boolean.valueOf(yytext()));
          }
        case 64: break;
        case 32: 
          { return newSymbol(this.CLASS);
          }
        case 65: break;
        case 10: 
          { return newSymbol(this.LT);
          }
        case 66: break;
        case 16: 
          { return newSymbol(this.RPAREN);
          }
        case 67: break;
        case 25: 
          { return newSymbol(this.GEQ);
          }
        case 68: break;
        case 8: 
          { return newSymbol(this.MOD);
          }
        case 69: break;
        case 1: 
          { /* ignore */
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return newSymbol(this.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
